const ARCHIVE_KEY = 'master-state';
const ARCHIVE_DB = 'babylon-flow-archive';
const clone = value => JSON.parse(JSON.stringify(value));
const canonicalArchive = () => clone(BABYLON_ARCHIVE);
const legacyStore = {
  get(key, fallback) { try { return JSON.parse(localStorage.getItem(`babylon-${key}`)) || fallback; } catch { return fallback; } },
  set(key, value) { localStorage.setItem(`babylon-${key}`, JSON.stringify(value)); }
};
const archiveDB = {
  open() { return new Promise((resolve, reject) => { const request = indexedDB.open(ARCHIVE_DB, 1); request.onupgradeneeded = () => request.result.createObjectStore('archive'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); },
  async get() { const db = await this.open(); return new Promise((resolve, reject) => { const request = db.transaction('archive').objectStore('archive').get(ARCHIVE_KEY); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); },
  async set(value) { const db = await this.open(); return new Promise((resolve, reject) => { const request = db.transaction('archive', 'readwrite').objectStore('archive').put(value, ARCHIVE_KEY); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); }
};
let people = [], events = [], quotes = [], npcs = [], morningReports = [], duoHistory = [], auditLog = [];
let archiveReady = false;
function currentArchive() { return { schemaVersion: BABYLON_ARCHIVE.schemaVersion, updatedAt: new Date().toISOString(), source: BABYLON_ARCHIVE.source, people, events, quotes, npcs, morningReports, duoHistory, auditLog }; }
function applyArchive(data) { const fallback = canonicalArchive(); people = data.people || fallback.people; events = data.events || fallback.events; quotes = data.quotes || fallback.quotes; npcs = data.npcs || fallback.npcs; morningReports = data.morningReports || []; duoHistory = data.duoHistory || []; auditLog = data.auditLog || []; }
function addAudit(action, detail = '') { auditLog.unshift({ id: `${Date.now()}-${Math.random().toString(16).slice(2)}`, at: new Date().toISOString(), action, detail }); auditLog = auditLog.slice(0, 500); }
async function loadArchive() {
  let archive;
  try { archive = await archiveDB.get(); } catch { archive = legacyStore.get('archive-fallback', null); }
  if (!archive) {
    const legacyPeople = legacyStore.get('people', null);
    archive = canonicalArchive();
    if (legacyPeople) {
      archive.people = legacyPeople; archive.events = legacyStore.get('events', archive.events); archive.quotes = legacyStore.get('quotes', archive.quotes); archive.npcs = legacyStore.get('npcs', archive.npcs); archive.morningReports = legacyStore.get('morning-reports', []); archive.duoHistory = legacyStore.get('duo-history', []);
      archive.auditLog = [{ id: 'legacy-migration', at: new Date().toISOString(), action: 'Migrated legacy local archive', detail: 'Moved localStorage data into the durable archive.' }];
    }
    try { await archiveDB.set(archive); } catch { legacyStore.set('archive-fallback', archive); }
  }
  applyArchive(archive); archiveReady = true; renderPeople(); renderMarket(); renderTimeline();
}
let activeModal = null;
const $ = (s) => document.querySelector(s);
const initials = (name) => name.split(' ').map(x => x[0]).join('').slice(0,2);
const title = (id) => people.find(p => p.id === id)?.alias || id;
const ACCESS_PHRASE = 'babylon2026';
const LOG_EMAIL_ENDPOINT = 'https://formsubmit.co/ajax/rogee.oc@gmail.com';

async function emailLog(kind, details) {
  const response = await fetch(LOG_EMAIL_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
    body: JSON.stringify({
      _subject: `Babylon Flow — ${kind}`,
      'Log type': kind,
      'Logged at': new Date().toLocaleString(),
      ...details
    })
  });
  const result = await response.json().catch(() => ({}));
  const needsActivation = /activat|confirm/i.test(result.message || '');
  if (!response.ok || ((result.success === false || result.success === 'false') && !needsActivation)) {
    throw new Error(result.message || 'Email could not be sent');
  }
  return { ...result, needsActivation };
}

function notifyLog(kind, details) {
  emailLog(kind, details)
    .then(result => toast(result.needsActivation
      ? 'LOGGED · CHECK EMAIL TO ACTIVATE DELIVERY'
      : 'LOGGED · EMAIL SENT'))
    .catch(() => toast('LOGGED LOCALLY · EMAIL NOT SENT'));
}

function setupAccessGate() {
  const gate = $('#accessGate');
  if (sessionStorage.getItem('babylon-access') === 'granted') { gate.classList.add('unlocked'); return; }
  $('#gateForm').onsubmit = event => {
    event.preventDefault();
    if ($('#accessPassword').value === ACCESS_PHRASE) {
      sessionStorage.setItem('babylon-access', 'granted');
      gate.classList.add('unlocked');
    } else {
      $('#gateError').textContent = 'ACCESS DENIED — CHECK THE PHRASE.';
      $('#accessPassword').select();
    }
  };
}

function renderPeople() {
  $('#peopleGrid').innerHTML = people.map(p => `
    <article class="person-card" style="--person:var(--${p.accent})" data-person="${p.id}" title="Open ${p.name}'s asset profile">
      <div class="avatar">${initials(p.alias)}</div><span class="animal">${p.animal} CLASS</span>
      <h3>${p.alias}</h3><div class="name">${p.name.toUpperCase()} · €${p.stock.toFixed(1)}</div>
      <div class="bars">
        ${statBar('AURA', p.stats.aura)}${statBar('CHAOS', p.stats.chaos)}${statBar('IBIZA', p.stats.ibiza)}
      </div><span class="person-xp">${p.stats.xp} XP</span>
    </article>`).join('');
  document.querySelectorAll('[data-person]').forEach(c => c.onclick = () => openPerson(c.dataset.person));
}
function statBar(label, value) { return `<div><div class="bar-label"><span>${label}</span><span>${value}</span></div><div class="bar"><span style="width:${Math.min(value,100)}%"></span></div></div>`; }
function renderMarket() {
  const best = [...people].sort((a,b) => b.stock-a.stock)[0], chaos = [...people].sort((a,b)=>b.stats.chaos-a.stats.chaos)[0];
  $('#marketCard').innerHTML = `<div class="market-main"><span class="micro-label">AFTER-HOURS BRIEFING</span><p><strong class="up">${best.alias} ▲ 11.7%</strong><br>Strong DJ guidance and unexpectedly competent Spanish have driven an upgrade in investor confidence.</p></div><div class="market-stats"><div><span class="micro-label">TOP ASSET</span><b>${best.alias}</b></div><div><span class="micro-label">CHAOS INDEX</span><b>${chaos.stats.chaos}/100</b></div><div><span class="micro-label">SHOE RESERVE</span><b>02</b></div></div>`;
}
function renderTimeline() {
  $('#timeline').innerHTML = events.map(e => `<article class="timeline-item"><div><span class="event-type">${e.type}</span></div><div><h3>${e.title}</h3><p>${e.description}</p></div><div class="event-meta">${e.location || 'FIELD UNKNOWN'}<br><strong>${e.change || 'LOGGED'}</strong><br>${e.time}</div></article>`).join('');
}
function save(action, detail) { if (action) addAudit(action, detail); const archive = currentArchive(); archiveReady && archiveDB.set(archive).catch(() => legacyStore.set('archive-fallback', archive)); renderPeople(); renderMarket(); renderTimeline(); }
function openModal(content, kind, wide=false) { activeModal = kind; $('#modalBody').innerHTML = content; $('#modal').classList.toggle('wide', wide); $('#backdrop').classList.add('open'); $('#modal').classList.add('open'); }
function closeModal() { $('#backdrop').classList.remove('open'); $('#modal').classList.remove('open'); $('#modal').classList.remove('wide'); activeModal = null; }
function toast(message) { const t = $('#toast'); t.textContent = message; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'), 2700); }
const peopleOptions = (multiple=false) => people.map(p=>`<option value="${p.id}">${p.alias} — ${p.name}</option>`).join('');

function eventModal() { openModal(`<h2 id="modalTitle">LOG EVENT</h2><p class="lede">Create a permanent record of an operational incident.</p><form id="eventForm"><div class="form-grid"><div><label>PEOPLE INVOLVED</label><select name="person">${peopleOptions()}</select></div><div><label>CATEGORY</label><select name="category"><option>RANDOM LORE</option><option>PARTY</option><option>CLUB</option><option>BEACH</option><option>FOOD</option><option>SPORT</option><option>LEGENDARY</option></select></div><div class="full"><label>INCIDENT TITLE</label><input required name="title" autocomplete="off" placeholder="The Supermarket Incident" maxlength="55"></div><div class="full"><label>WHAT HAPPENED</label><textarea name="description" required placeholder="Keep it brief. The timeline is watching." maxlength="180"></textarea></div><div><label>LOCATION</label><input name="location" placeholder="JÁVEA HQ" maxlength="30"></div><div><label>XP AWARD</label><select name="xp"><option value="25">+25 XP</option><option value="50" selected>+50 XP</option><option value="100">+100 XP</option><option value="150">+150 XP</option></select></div></div><button class="submit-button">COMMIT TO THE ARCHIVE →</button></form>`, 'event');
  $('#eventForm').onsubmit = e => { e.preventDefault(); const d = new FormData(e.target), xp=+d.get('xp'), p=people.find(x=>x.id===d.get('person')), location=(d.get('location')||'FIELD UNKNOWN').toUpperCase(); p.stats.xp += xp; p.stock = +(p.stock * (1 + (Math.random()*.06-.015))).toFixed(1); events.unshift({ id:Date.now(), type:d.get('category'), title:d.get('title'), description:d.get('description'), location, people:[p.id], time:'JUST NOW', change:`+${xp} XP`}); save('Event logged', d.get('title')); closeModal(); notifyLog('Event logged', { 'Person involved': p.alias, Category: d.get('category'), Title: d.get('title'), 'What happened': d.get('description'), Location: location, 'XP award': `+${xp} XP` }); };
}
function quoteModal() { openModal(`<h2 id="modalTitle">LOG QUOTE</h2><p class="lede">The evidentiary archive has no context limit. You should.</p><form id="quoteForm"><div class="form-grid"><div class="full"><label>THE QUOTE</label><textarea required name="quote" placeholder="A sentence future generations will misunderstand." maxlength="180"></textarea></div><div><label>SPEAKER</label><select name="speaker">${peopleOptions()}<option value="UNKNOWN">UNKNOWN ENTITY</option></select></div><div><label>CONTEXT</label><input name="context" placeholder="e.g. 04:00 taxi debate" maxlength="45"></div></div><button class="submit-button">SEAL THE EVIDENCE →</button></form>`, 'quote');
  $('#quoteForm').onsubmit = e => { e.preventDefault(); const d=new FormData(e.target), speaker=title(d.get('speaker')), context=d.get('context'); quotes.unshift({id:Date.now(), quote:d.get('quote'),speaker,context,time:'JUST NOW'}); events.unshift({id:Date.now()+1,type:'QUOTE',title:`“${d.get('quote').slice(0,48)}${d.get('quote').length>48?'…':''}”`,description:`Entered into evidence by ${speaker}${context ? ` · ${context}` : ''}.`,location:'QUOTE ARCHIVE',time:'JUST NOW',change:'RECORDED'}); save('Quote logged', d.get('quote').slice(0, 80)); closeModal(); notifyLog('Quote logged', { Speaker: speaker, Quote: d.get('quote'), Context: context || 'Not supplied' }); };
}
function questModal(quest = BABYLON_QUESTS[Math.floor(Math.random()*BABYLON_QUESTS.length)]) { openModal(`<h2 id="modalTitle">SIDE QUEST</h2><p class="lede">Optional mission. Mandatory lore potential.</p><div class="quest-card"><span class="rarity">${quest.rarity} ASSIGNMENT</span><h3>${quest.mission}</h3><div class="quest-details"><span>LOCATION <b>${quest.place}</b></span><span>REWARD <b>+${quest.xp} XP</b></span></div></div><div class="quest-actions"><button class="secondary-button" id="reroll">REROLL</button><button class="submit-button" id="completeQuest">COMPLETE QUEST</button></div>`, 'quest');
  $('#reroll').onclick=()=>questModal(); $('#completeQuest').onclick=()=>{ const p=people[Math.floor(Math.random()*people.length)];p.stats.xp+=quest.xp;events.unshift({id:Date.now(),type:'SIDE QUEST',title:'Side quest completed',description:`${p.alias} completed the mission: ${quest.mission}`,location:quest.place,time:'JUST NOW',change:`+${quest.xp} XP`});save('Side quest completed',quest.mission);closeModal();toast(`QUEST COMPLETE · ${p.alias} +${quest.xp} XP`);};
}
function courtModal() { openModal(`<h2 id="modalTitle">BABYLON COURT</h2><p class="lede">An independent judicial body with no standards whatsoever.</p><form id="courtForm"><div class="form-grid"><div><label>THE ACCUSED</label><select name="accused">${peopleOptions()}</select></div><div><label>CASE TYPE</label><select name="type"><option>GENERAL MISCONDUCT</option><option>SPANISH CRIMES</option><option>FISCAL NEGLIGENCE</option><option>LORE VIOLATION</option></select></div><div class="full"><label>THE ACCUSATION</label><textarea required name="accusation" placeholder="What exactly are we pretending happened?" maxlength="160"></textarea></div><div class="full"><label>DEFENSE (OPTIONAL / IGNORED)</label><input name="defense" placeholder="An attempt will be filed."></div></div><button class="submit-button">SUBMIT TO VAR →</button></form>`, 'court');
  $('#courtForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);courtProcessing(d);};
}
function courtProcessing(data) { $('#modalBody').innerHTML=`<div class="court-stage"><span class="micro-label">BABYLON JUDICIARY / LIVE</span><div class="court-symbol">⚖</div><h3 id="courtStatus">ANALYSING EVIDENCE…</h3><p>Cross-referencing vibes, witness statements and the shoe archive.</p></div>`; setTimeout(()=>$('#courtStatus').textContent='CHECKING VAR…',900); setTimeout(()=>$('#courtStatus').textContent='CONSULTING BABYLON LAW…',1800); setTimeout(()=>courtVerdict(data),2850); }
function courtVerdict(data) { const accused=people.find(p=>p.id===data.get('accused')); const outcomes=['GUILTY','TECHNICALLY GUILTY','GUILTY','NOT GUILTY','CASE DISMISSED']; const verdict=outcomes[Math.floor(Math.random()*outcomes.length)], sentence=COURT_SENTENCES[Math.floor(Math.random()*COURT_SENTENCES.length)]; if(verdict!=='NOT GUILTY'&&verdict!=='CASE DISMISSED') {accused.stats.chaos=Math.min(100,accused.stats.chaos+5);accused.stock=+(accused.stock*.96).toFixed(1);} events.unshift({id:Date.now(),type:'COURT',title:`${accused.alias}: ${verdict}`,description:`Case: ${data.get('accusation')} Sentence: ${verdict==='NOT GUILTY'||verdict==='CASE DISMISSED'?'The court has somehow allowed this.':sentence}`,location:'BABYLON COURT',time:'JUST NOW',change:verdict==='GUILTY'?'−4% STOCK':'VERDICT FILED'});save('Court verdict',`${accused.alias}: ${verdict}`); $('#modalBody').innerHTML=`<div class="court-stage"><span class="micro-label">CASE #${String(Date.now()).slice(-5)} / FINAL</span><div class="verdict"><span class="verdict-label">VERDICT</span><h3>${verdict}</h3><p>After reviewing all available vibes, the court finds ${accused.alias} ${verdict.toLowerCase()}. ${verdict==='NOT GUILTY'?'This establishes no precedent.':`Sentence: ${sentence}`}</p></div><button class="submit-button" id="closeVerdict">ACCEPT BABYLON LAW</button></div>`;$('#closeVerdict').onclick=()=>{closeModal();toast('VERDICT ARCHIVED · THE LAW PREVAILS');}; }
function openPerson(id) { const p=people.find(x=>x.id===id); openModal(`<h2 id="modalTitle">${p.alias}</h2><p class="lede">${p.name.toUpperCase()} · ${p.animal} CLASS · CURRENT ASSET €${p.stock.toFixed(1)}</p><div class="form-grid">${[['AURA',p.stats.aura],['RELIABILITY',p.stats.reliability],['SPANISH FLUENCY',p.stats.spanish],['CHAOS',p.stats.chaos],['FISCAL RESPONSIBILITY',p.stats.fiscal],['IBIZA PERFORMANCE',p.stats.ibiza],['SEX APPEAL',p.stats.appeal],['EXPERIENCE',`${p.stats.xp} XP`]].map(([a,b])=>`<div class="quest-card" style="padding:14px"><span class="micro-label">${a}</span><h3 style="margin:7px 0 0;font-size:25px">${b}</h3></div>`).join('')}</div>`, 'person'); }

const escapeHTML = value => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function wheelModal() {
  openModal(`<div class="wheel-stage"><span class="micro-label">BABYLON RANDOMIZATION ENGINE / RARE DROPS ENABLED</span><h2 id="modalTitle">WHEEL OF BAD<br>DECISIONS</h2><p class="lede">The wheel has no memory, no mercy and a 12% chance of legend.</p><div class="wheel-wrap"><div class="wheel-pointer"></div><div class="wheel-disc" id="wheelDisc"></div></div><div class="wheel-result" id="wheelResult">SPIN TO ACCEPT YOUR FATE.</div><button class="submit-button" id="spinWheel">SPIN THE WHEEL →</button></div>`, 'wheel');
  $('#spinWheel').onclick = () => { const outcome = BABYLON_WHEEL[Math.floor(Math.random()*BABYLON_WHEEL.length)]; const disc=$('#wheelDisc'); disc.style.transform=`rotate(${1800 + Math.floor(Math.random()*1800)}deg)`; $('#spinWheel').disabled=true; $('#spinWheel').textContent='DECISION IN PROGRESS…'; setTimeout(()=>{ $('#wheelResult').innerHTML=`${outcome.legendary ? '<span class="legendary-result">✦ LEGENDARY DROP ✦<br>' : ''}${outcome.text}${outcome.legendary ? '</span>' : ''}`; $('#spinWheel').disabled=false; $('#spinWheel').textContent='SPIN AGAIN →'; events.unshift({id:Date.now(),type:outcome.legendary?'LEGENDARY':'BAD DECISION',title:outcome.text,description:'Assigned by the Wheel of Bad Decisions. Appeals are not accepted.',location:'FIELD SYSTEMS',time:'JUST NOW',change:outcome.legendary?'+250 XP':'MISSION ISSUED'}); save(); },4700); };
}
function exchangeModal() {
  const total=people.reduce((sum,p)=>sum+p.stock,0), sorted=[...people].sort((a,b)=>b.stock-a.stock);
  const headlines = BABYLON_HEADLINES.map(h=>`<div class="headline"><span>BFSE FLASH</span> — ${h}</div>`).join('');
  openModal(`<h2 id="modalTitle">TRIP STOCK EXCHANGE</h2><p class="lede">Every person is a company. None of these securities are regulated.</p><div class="portfolio"><span class="micro-label">GROUP PORTFOLIO<br><b>€${total.toFixed(1)}</b></span><span class="micro-label">MARKET LEADER<br><b>${sorted[0].alias}</b></span></div><div class="stock-table">${sorted.map((p,index)=>{const move=((p.stats.xp%25)-10.6).toFixed(1);return `<div class="stock-row"><b>${p.alias}</b><span>€${p.stock.toFixed(1)}</span><strong class="${move>=0?'up':'down'}">${move>=0?'▲':'▼'} ${Math.abs(move)}%</strong><span>${index===0?'UPGRADED ON VIBES':'ANALYSTS REMAIN CONCERNED'}</span></div>`}).join('')}</div><h3 style="margin:24px 0 8px;font:18px var(--display)">BLOOMBERG-ADJACENT</h3>${headlines}</div>`, 'exchange', true);
}
function npcModal() {
  const cards = npcs.length ? `<div class="npc-grid">${npcs.map(n=>`<article class="npc-card"><span class="micro-label">${escapeHTML(n.nationality)} · ${escapeHTML(n.where)}</span><h3>${escapeHTML(n.nickname)}</h3><span class="danger">DANGER LEVEL: ${escapeHTML(n.danger)}</span><p>${escapeHTML(n.lore)}</p><p><b>SIDE QUEST:</b> ${escapeHTML(n.quest)}<br><b>REAPPEARANCE ODDS:</b> ${escapeHTML(n.odds)}</p></article>`).join('')}</div>` : '<p class="lede">No memorable entities logged yet. This is statistically temporary.</p>';
  openModal(`<h2 id="modalTitle">NPC GENERATOR</h2><p class="lede">Turn a memorable stranger into permanent canon.</p><form id="npcForm"><div class="form-grid"><div><label>NICKNAME</label><input required name="nickname" placeholder="The Espresso Oracle"></div><div><label>NATIONALITY</label><input required name="nationality" placeholder="ITALIAN"></div><div><label>WHERE ENCOUNTERED</label><input required name="where" placeholder="BEACH BAR"></div><div><label>DANGER LEVEL</label><select name="danger"><option>LOW / MYSTERIOUS</option><option>MEDIUM / UNPREDICTABLE</option><option>HIGH / KEEP EYES OPEN</option><option>FINAL BOSS</option></select></div><div class="full"><label>LORE</label><textarea required name="lore" maxlength="180" placeholder="What made this person canon?"></textarea></div><div><label>SIDE QUEST</label><input required name="quest" placeholder="Find their cousin"></div><div><label>LIKELIHOOD OF REAPPEARANCE</label><select name="odds"><option>3% / A MIRACLE</option><option>27% / SAME BAR THEORY</option><option>64% / THEY KNOW WHERE WE STAY</option><option>100% / INEVITABLE</option></select></div></div><button class="submit-button">ADD TO CANON →</button></form><h3 style="margin:32px 0 12px;font:18px var(--display)">KNOWN ENTITIES</h3>${cards}`, 'npc', true);
  $('#npcForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);const n=Object.fromEntries(d.entries());n.id=Date.now();npcs.unshift(n);events.unshift({id:Date.now()+1,type:'NPC ENCOUNTER',title:`NPC logged: ${n.nickname}`,description:n.lore,location:n.where.toUpperCase(),time:'JUST NOW',change:'CANONIZED'});save('NPC canonized',n.nickname);npcModal();toast('NPC CANONIZED · SIDE QUEST AVAILABLE');notifyLog('NPC canonized',{Nickname:n.nickname,Nationality:n.nationality,'Where encountered':n.where,'Danger level':n.danger,Lore:n.lore,'Side quest':n.quest,'Reappearance odds':n.odds});};
}
function varModal() { openModal(`<h2 id="modalTitle">VAR FOR ARGUMENTS</h2><p class="lede">Two accounts enter. Babylon Law leaves with the truth.</p><form id="varForm"><div class="form-grid"><div><label>WITNESS A</label><select name="a">${peopleOptions()}</select></div><div><label>WITNESS B</label><select name="b">${peopleOptions()}</select></div><div class="full"><label>WITNESS A'S ACCOUNT</label><textarea required name="accountA" placeholder="What definitely happened, according to them?"></textarea></div><div class="full"><label>WITNESS B'S ACCOUNT</label><textarea required name="accountB" placeholder="The completely different version."></textarea></div></div><button class="submit-button">SEND TO VAR →</button></form>`, 'var'); $('#varForm').onsubmit=e=>{e.preventDefault();varProcessing(new FormData(e.target));}; }
function varProcessing(data) { $('#modalBody').innerHTML=`<div class="court-stage"><span class="micro-label">BABYLON VAR / UNBIASED IN THEORY</span><div class="court-symbol">◉</div><h3 id="varStatus">LOADING EVIDENCE…</h3><p id="varSub">Synchronising witness confidence levels.</p><div class="progress-line"><span id="varProgress"></span></div></div>`; const stages=['CALIBRATING THE VIBE-O-METER…','CHECKING VAR…','REVIEWING 14 PIXELS OF EVIDENCE…','CONSULTING THE TAXI DRIVER…']; stages.forEach((s,i)=>setTimeout(()=>{$('#varStatus').textContent=s;$('#varProgress').style.width=`${(i+1)*25}%`;},i*2500)); setTimeout(()=>varVerdict(data),10000); }
function varVerdict(data) { const a=title(data.get('a')), b=title(data.get('b')), decisions=[`${a} was technically correct, but spiritually suspicious.`,`${b}'s version is accepted because it has better pacing.`, 'Both accounts are rejected. The real culprit is the group chat.', 'After frame-by-frame review: nobody remembers anything, which is legally binding.']; const decision=decisions[Math.floor(Math.random()*decisions.length)]; events.unshift({id:Date.now(),type:'VAR DECISION',title:'Argument submitted to VAR',description:decision,location:'BABYLON REVIEW ROOM',time:'JUST NOW',change:'FINAL DECISION'});save();$('#modalBody').innerHTML=`<div class="court-stage"><span class="micro-label">VAR DECISION / ABSOLUTELY FINAL</span><div class="verdict"><span class="verdict-label">ON-FIELD RULING</span><h3>DECISION ISSUED</h3><p>${decision}</p><p><small>${a}: “${escapeHTML(data.get('accountA'))}”<br>${b}: “${escapeHTML(data.get('accountB'))}”</small></p></div><button class="submit-button" id="closeVerdict">ACCEPT REALITY</button></div>`;$('#closeVerdict').onclick=closeModal; }
function loreModal() { const entries=events.slice(0,18).map((e,i)=>`<article class="lore-entry"><span class="micro-label">CHAPTER ${String(i+1).padStart(2,'0')} · ${escapeHTML(e.time)}</span><h3>The ${escapeHTML(e.title)} Incident</h3><p><b>LOCATION:</b> ${escapeHTML(e.location||'UNKNOWN')}<br><b>PARTICIPANTS:</b> ${(e.people||[]).map(title).join(', ')||'CLASSIFIED'}</p><p>${escapeHTML(e.description)}</p><p><b>EYEWITNESS ACCOUNT:</b> “It seemed reasonable at the time.”<br><b>CONSEQUENCE:</b> ${escapeHTML(e.change||'Historical record amended.')}</p></article>`).join(''); openModal(`<h2 id="modalTitle">THE LORE BOOK</h2><p class="lede">An increasingly inaccurate historical record of the España 2026 campaign.</p><div class="lore-grid">${entries}</div>`, 'lore', true); }
function duoModal() { const pool=[...people].sort(()=>Math.random()-.5); const [a,b]=pool; const mission=BABYLON_DUOS[Math.floor(Math.random()*BABYLON_DUOS.length)]; openModal(`<h2 id="modalTitle">RANDOM DUO MISSION</h2><p class="lede">The algorithm has separated the usual suspects.</p><div class="duo-pair"><span class="micro-label">CO-OP UNIT ASSIGNED</span><h3>${a.alias} × ${b.alias}</h3><p>${mission}</p><span class="rarity">REWARD: +80 XP EACH · +1 SHARED MEMORY</span></div><div class="quest-actions"><button class="secondary-button" id="rerollDuo">REROLL PAIR</button><button class="submit-button" id="acceptDuo">ACCEPT MISSION</button></div>`, 'duo'); $('#rerollDuo').onclick=duoModal; $('#acceptDuo').onclick=()=>{a.stats.xp+=80;b.stats.xp+=80;duoHistory.unshift({id:Date.now(),pair:[a.id,b.id],mission});events.unshift({id:Date.now()+1,type:'DUO MISSION',title:`${a.alias} × ${b.alias}`,description:mission,location:'CO-OP FIELD',time:'JUST NOW',change:'+80 XP EACH'});save();closeModal();toast('DUO DEPLOYED · NO EXCUSES');}; }
function morningModal() { const reports=morningReports.length ? morningReports.map(r=>`<article class="report-card ${/contradict/i.test(r.fragment)?'contradiction':''}"><span class="micro-label">${escapeHTML(r.time)} · ANONYMOUS</span><p>“${escapeHTML(r.fragment)}”</p></article>`).join('') : '<p class="lede">The official record has no testimony yet. A rare opportunity.</p>'; openModal(`<h2 id="modalTitle">MORNING AFTER REPORT</h2><p class="lede">Anonymous fragments are reconstructed into an official account. Contradictions are a feature.</p><form id="morningForm"><div class="form-grid"><div><label>APPROX. TIME</label><input required name="time" placeholder="e.g. 03:40"></div><div><label>MEMORY CONFIDENCE</label><select name="confidence"><option>HIGH / ALLEGEDLY</option><option>MEDIUM / BLURRY</option><option>LOW / VIBES ONLY</option></select></div><div class="full"><label>WHAT DO YOU REMEMBER?</label><textarea required name="fragment" placeholder="Submit only a fragment. The bureau will do the rest."></textarea></div></div><button class="submit-button">FILE ANONYMOUS TESTIMONY →</button></form><div class="quest-actions" style="margin-top:12px"><button class="secondary-button" id="reconstruct">RECONSTRUCT OFFICIAL ACCOUNT</button></div><h3 style="margin:28px 0 12px;font:18px var(--display)">RAW TESTIMONY</h3>${reports}`, 'morning', true); $('#morningForm').onsubmit=e=>{e.preventDefault();const r=Object.fromEntries(new FormData(e.target).entries());r.id=Date.now();morningReports.push(r);save('Morning testimony filed',r.time);morningModal();notifyLog('Morning testimony',{Time:r.time,'Memory confidence':r.confidence,Testimony:r.fragment});}; $('#reconstruct').onclick=reconstructMorning; }
function reconstructMorning() { const sorted=[...morningReports].sort((a,b)=>a.time.localeCompare(b.time)); const text=sorted.length ? sorted.map((r,i)=>`${r.time} — ${r.fragment}`).join(' Then, ') : 'No witness testimony has been filed. The official account therefore reads: everyone went home early and made excellent decisions.'; const contradiction=morningReports.length>1 && morningReports.some(r=>/not|never|no /i.test(r.fragment)); $('#modalBody').innerHTML=`<h2 id="modalTitle">OFFICIAL ACCOUNT</h2><p class="lede">Reconstructed by the Babylon Bureau of Unreliable Narratives.</p><div class="report-card ${contradiction?'contradiction':''}"><span class="micro-label">CHRONOLOGICAL RECONSTRUCTION</span><p>${escapeHTML(text)}</p>${contradiction?'<p class="danger">⚠ CONTRADICTORY TESTIMONY FLAGGED — THE TRUTH HAS BEEN QUARANTINED.</p>':''}</div><button class="submit-button" id="closeReport">FILE AS FACT</button>`;$('#closeReport').onclick=closeModal; }
function wrappedModal() { const liability=[...people].sort((a,b)=>b.stats.chaos-a.stats.chaos)[0], km=events.length*3.7+31, phrase=quotes[0]?.quote||'No quote on record', late=events.filter(e=>/0[0-5]:/.test(e.time)).length, comeback=[...people].sort((a,b)=>b.stock-a.stock)[0]; openModal(`<div class="wrapped-hero"><span class="micro-label">BABYLON FLOW PRESENTS</span><h2 id="modalTitle">TRIP WRAPPED<br>2026</h2><p class="lede">A provisional finale, updated as the lore gets worse.</p></div><div class="wrapped-stats"><div><span class="micro-label">BIGGEST LIABILITY</span><b>${liability.alias}</b></div><div><span class="micro-label">KM TRAVELLED*</span><b>${km.toFixed(0)}</b></div><div><span class="micro-label">LATEST BEDTIME</span><b>${late?'05:42':'PENDING'}</b></div><div><span class="micro-label">MOST SIDE QUESTS</span><b>${duoHistory.length||'0'} DUOS</b></div><div><span class="micro-label">BIGGEST COMEBACK</span><b>${comeback.alias}</b></div><div><span class="micro-label">QUOTE OF THE TRIP</span><b style="font-size:16px">“${escapeHTML(phrase)}”</b></div></div><p class="lede" style="margin-top:16px">*Estimated from incident density, taxi lore and an unverified beach walk.</p>`, 'wrapped', true); }

document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>({event:eventModal,quote:quoteModal,quest:questModal,court:courtModal,wheel:wheelModal,exchange:exchangeModal,npc:npcModal,var:varModal,lore:loreModal,duo:duoModal,morning:morningModal,wrapped:wrappedModal}[b.dataset.open]()));
$('#closeModal').onclick=closeModal; $('#backdrop').onclick=closeModal; document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
$('#viewAll').onclick=()=>{ document.querySelector('.people-grid').scrollIntoView({behavior:'smooth',block:'start'}); toast('ALL 7 ACTIVE ASSETS DISPLAYED'); };
function archiveModal() {
  openModal(`<h2 id="modalTitle">ARCHIVE CONTROL</h2><p class="lede">This device keeps an IndexedDB master archive. Export a backup after meaningful lore; import restores a previously exported archive.</p><div class="quest-card"><span class="micro-label">ARCHIVE STATUS</span><h3>${events.length} INCIDENTS · ${quotes.length} QUOTES</h3><p class="lede" style="margin:8px 0 0">${npcs.length} NPCS · ${morningReports.length} TESTIMONIES · ${auditLog.length} AUDIT ENTRIES</p></div><div class="quest-actions" style="margin-top:14px"><button class="secondary-button" id="exportArchive">EXPORT JSON</button><label class="secondary-button" style="display:grid;place-items:center;padding:12px">IMPORT JSON<input id="importArchive" type="file" accept="application/json" hidden></label></div><p class="lede" style="margin-top:18px">Forward incoming Babylon emails here and I’ll add them to the checked-in canonical ledger for the next deployment.</p>`, 'archive');
  $('#exportArchive').onclick = () => { const blob = new Blob([JSON.stringify(currentArchive(), null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `babylon-flow-archive-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(link.href); toast('ARCHIVE BACKUP EXPORTED'); };
  $('#importArchive').onchange = event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = async () => { try { const incoming = JSON.parse(reader.result); if (!Array.isArray(incoming.people) || !Array.isArray(incoming.events) || !Array.isArray(incoming.quotes)) throw new Error('Invalid archive'); applyArchive(incoming); addAudit('Archive restored', file.name); await archiveDB.set(currentArchive()); renderPeople(); renderMarket(); renderTimeline(); closeModal(); toast('ARCHIVE RESTORED · CANON PRESERVED'); } catch { toast('IMPORT REJECTED · INVALID ARCHIVE'); } }; reader.readAsText(file); };
}
$('#adminButton').onclick=archiveModal;
$('#clearData').onclick=()=>{if(confirm('Reset this device to the checked-in canonical ledger?')){applyArchive(canonicalArchive());addAudit('Archive reset','Restored canonical ledger');save();toast('CANONICAL LEDGER RESTORED');}};
loadArchive();
setupAccessGate();
